### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by wamapi89** [robertjoosten/video2mocap#1]
Hello,
I tried to run the video2mocap.py and it generates this error: 

INFO | ---- HMR ----
INFO | Command:               python3.exe -m export --img_dir C:\Users\wafiy\Documents\video2mocap-master\output\temp\images_data --json_dir C:\Users\wafiy\Documents\video2mocap-master\output\temp\openpose_data --log_dir C:\Users\wafiy\Documents\video2mocap-master\output --output_path C:\Users\wafiy\Documents\video2mocap-master\output\temp\hmr_data.json
Traceback (most recent call last):
  File "video2mocap.py", line 188, in <module>
    config.python3_exe,
  File "video2mocap.py", line 150, in video2mocap
    subprocess.check_call(hmr_command, cwd=HMR_DIR)
  File "C:\Users\wafiy\Anaconda3\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\wafiy\Anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\wafiy\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\wafiy\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

I am using the python version:
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32

**Comment by tung-nguyen-uet** [comment]
I'm facing the exact same error.
I tried to look for python3.exe in my installed folder on Window, but there is no such file.
Could anyone tell my how to call 'python3,exe' on Windows 10?
Thanks in advance!

**Comment by robertjoosten** [comment]
Sorry guys, I've only just noticed this issue. This script expect you to have our python3.exe in a path that is accessible in the PATH environment variable. It is coming for people that have python2 and 3 installed at the same time to rename the python.exe to python3.exe to ensure you can choose which python you would like to use.

That being said you can use the python3_exe argument to link to the full path of your python3 executable.
