### ISSUE TITLE
Stuck with mayapy importing dependencies

### ISSUE THREAD

**Issue by tung-nguyen-uet** [robertjoosten/video2mocap#2]
Hi guys,
I'm really interested in your work, and I think your work is really helpful for mocap community.
I tried to run your code as a whole after installing all requirements, but I doesn't work. 
After narrowing down the issue, I found that there is problem with mayapy when it tries to import some dependency ('absl', 'six').
In conclusion, I finished the phase with hmr model and get the json file. 
- Could you clarify how do I run the command with 'mayapy.exe'?
- Or, is there the way that I can manually import the json file to maya?

Thanks in advance!

**Comment by robertjoosten** [comment]
Hello,

I've only just noticed this issue, so apologies for the delay. Make sure that your site packages for you standard python are available in Maya. You can set this up in the userSetup.py for example. If you prefer not to do this you can have a look at the maya-pip package on my github, this will allow you to install absl dependancies into the site packages of Maya itself.

Hope that will solve the issue.
