### ISSUE TITLE
linux version?

### ISSUE THREAD

**Issue by HHIR** [robertjoosten/video2mocap#3]
It seems amazing work, but is it possible to run this code on linux?

**Comment by melMass** [comment]
Yes, you just have to build the dependencies yourself: 
- **FFmpeg** using your package manager ( pacman on arch or brew on mac )
- **HMR**: Simply follow the bat script it's only about cloning the repo and downloading [models](https://people.eecs.berkeley.edu/~kanazawa/cachedir/hmr/models.tar.gz) in its `models` folder
- **OpenPose** only provides windows binaries but can be compiled on Linux and OSX from source (CPU only for the later...), they provide a deps installer in the `3rdparty` folder for OSX and the CMake files has Linux rules (only tested on Ubuntu and CentOS)

**Comment by robertjoosten** [comment]
Thank you @melMass for you input.
I don't have a linux work station so won't be able to offer any support there unfortunately.
