### ISSUE TITLE
Running on other 2D detectors

### ISSUE THREAD

**Issue by timtensor** [robertjoosten/video2mocap#5]
Hi as far as i understand the main function of  `2d detector` is to basically get the bounding box. Is it possible then to use other 2D detectors ??? Like `simpleHRnet` and `posenet`  [simpleHrNet](https://github.com/stefanopini/simple-HRNet) and [posenet](https://github.com/rwightman/posenet-python)

**Comment by robertjoosten** [comment]
Hi timtensor, You are correct. OpenPose bit of the code is used to extract a bounding box wouldn't see why you wouldn't be able to use other software to extract the bounding box.
